version: '3.8'
services:
  html2md.app:
    container_name: html2md.app
    image: golang:latest
    restart: always
    volumes:
      - ${PWD}:/app:rw
    working_dir: /app
    command: ls -acl
    env_file:
      - ${PWD}/.env
    ports:
      - "8080:8080"
    entrypoint: /app/scripts/entrypoint.sh
networks:
  html2md.networks:
    external: true
